/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Grid: (() => {
      const name = "Grid";
      return defineComponent(
        world,
        {
          grid_id: RecsType.Number,
          width: RecsType.Number,
          height: RecsType.Number,
          start_time: RecsType.Number,
          player_id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Mine: (() => {
      const name = "Mine";
      return defineComponent(
        world,
        {
          remaining: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Square: (() => {
      const name = "Square";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
          hidden: RecsType.Boolean,
          mine: RecsType.Boolean,
          flag: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Moves: (() => {
      const name = "Moves";
      return defineComponent(
        world,
        {
          counter: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Level: (() => {
      const name = "Level";
      return defineComponent(
        world,
        {
          difficulty: RecsType.Unknown,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
